# config.py
import os

# Set your API keys here
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GITHUB_ACCESS_TOKEN=os.getenv("GITHUB_ACCESS_TOKEN")
GITHUB_REPOSITORY=os.getenv("GITHUB_REPOSITORY")